version: "3.8"

services:

  web: &web
    container_name: web
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        DJANGO_ENV: 'dev'
    networks:
      - webnet
      - nginx_network
    expose:
      - 8000
    volumes:
      - ./eshop:/code
      - ./config:/config
    environment:
      DJANGO_DEBUG: 1
      DATABASE_PORT: '5432'
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/dev_db'
      DATABASE_HOST: 'db'
    env_file:
      - ./eshop/.env
    restart: on-failure
    depends_on:
      - redis
      - db
      - mailhog
    command: sh /runserver.sh
    links:
      - 'mailhog'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/admin/login/"]
      interval: 1m
      timeout: 5s
      retries: 2


  db:
    container_name: db
    image: postgis/postgis:12-master
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet
    expose:
      - 5432
    env_file: ./eshop/.env
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev_db'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  estorehouse:
    container_name: estorehouse
    build:
      context: .
      dockerfile: ./docker/estorehouse/Dockerfile
      args:
        DJANGO_ENV: 'dev'
    networks:
      - nginx_network
      - estorehouse_network
      - webnet
    ports:
      - 8001:8001
    volumes:
      - ./estorehouse:/code
      - ./config:/config
    environment:
      DJANGO_DEBUG: 1
      DATABASE_PORT: '5432'
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/dev_db_estorehouse'
      DATABASE_HOST: 'db_estorehouse'
    env_file:
      - ./estorehouse/.env
    restart: on-failure
    depends_on:
      - db_estorehouse
    command: sh /runserver.sh
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:8001/admin/login/" ]
      interval: 1m
      timeout: 5s
      retries: 2

  db_estorehouse:
    container_name: db_estorehouse
    image: postgis/postgis:12-master
    restart: on-failure
    volumes:
      - db-data_estorehouse:/var/lib/postgresql/data
    networks:
      - estorehouse_network
    expose:
      - 5432
    env_file: ./estorehouse/.env
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev_db_estorehouse'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    networks:
      - nginx_network
    ports:
      - 80:80
      - 5555:5555
      - 8025:8025
    depends_on:
      - web
      - flower
      - mailhog
    healthcheck:
      test: ["CMD-SHELL", "ps ax", "|" ,"grep -v grep", "|" ,"grep nginx",  "||", "exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3


  redis:
    container_name: redis
    image: redis:5.0.6-alpine
    restart: on-failure
    networks:
      - webnet
    expose:
      - 6379
    volumes:
      - redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.0-alpine
    restart: on-failure
    networks:
      - webnet
    expose:
      - 4369
      - 5671
      - 5672
      - 15672
      - 25672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 15s
      retries: 1


  celery:
    <<: *web
    container_name: celery
    restart: on-failure
    depends_on:
      - web
      - estorehouse
      - rabbitmq
      - redis
      - db
    expose: []
    networks:
      - webnet
      - estorehouse_network
    environment:
      C_FORCE_ROOT: 'true'
      CHECK_WEB: 'true'
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/dev_db'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
      REDIS_URL: 'redis://redis:6379'
      REDIS_CACHE: 'redis:6379'
      AMQP_URL: 'amqp://rabbitmq:5672'
      WEB_HOST: 'web'
      WEB_PORT: '8000'
    command: celery -A core worker -B -l INFO
    healthcheck:
      test: ["CMD-SHELL", "ps ax", "|" ,"grep -v grep", "|" ,"grep celery",  "||", "exit 1"]
      interval: 1m
      timeout: 5s
      retries: 2


  flower:
    image: mher/flower:0.9.5
    container_name: flower
    networks:
      - webnet
      - nginx_network
    expose:
      - 5555
    depends_on:
      - celery
      - redis
      - rabbitmq
      - db
#    command: [ "--app core", "--port=5555", "--url_prefix=flower", "--broker=amqp://rabbitmq:5672", "--broker_api=amqp://rabbitmq:15672//" ]
#    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    command: [ 'flower', '--broker=amqp://rabbitmq:5672', '--port=5555' ]


  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    command: [ "-smtp-bind-addr", "0.0.0.0:25" ]
    user: root
    restart: always
    networks:
      - webnet
      - nginx_network
    expose:
      - 25
      - 8025
    healthcheck:
      test: [ "CMD", "echo", "|", "telnet", "127.0.0.1 25" ]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - webnet
      - estorehouse_network
    depends_on:
      - db
      - db_estorehouse
    restart: unless-stopped


networks:
  webnet:
  nginx_network:
  estorehouse_network:

volumes:
  db-data:
  db-data_estorehouse:
  rabbitmq_data:
  redis:
