# Generated by Django 4.1.7 on 2023-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("stock", models.PositiveIntegerField(blank=True)),
                (
                    "isbn_no",
                    models.CharField(db_index=True, default="isbn_no", max_length=50),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
